SELECT * FROM SEMANTIC_VIEW(
    DEMO.DEMO.THERMAL_SENSOR_SEMANTIC_VIEW
    DIMENSIONS THERMAL_SENSORS.DEVICE_HOST, THERMAL_SENSORS.READING_HOUR
    METRICS THERMAL_SENSORS.AVG_CO2, THERMAL_SENSORS.AVG_HUMIDITY, THERMAL_SENSORS.AVG_PRESSURE,
            THERMAL_SENSORS.AVG_TEMPERATURE, THERMAL_SENSORS.AVG_VOC,
            THERMAL_SENSORS.MIN_TEMPERATURE , THERMAL_SENSORS.MAX_TEMPERATURE,
            THERMAL_SENSORS.READING_COUNT
  )
  order by reading_hour desc;
